services:
  ontime:
    container_name: ontime
    image: getontime/ontime:latest
    ports:
      - '4001:4001/tcp'
      # only needed when the OSC input integration is enabled
      - '8888:8888/udp'
    volumes:
      - './ontime-data:/data/'
    environment:
      - TZ=Asia/Singapore
    restart: unless-stopped
