packages:
  - apps/*
  - packages/*

catalog:
  '@types/node': 22.19.11
  rimraf: 6.1.3
  ts-essentials: 10.2.1
  typescript: 7.0.2
  vitest: 4.1.10

allowBuilds:
  '@parcel/watcher': true
  '@sentry/cli': false
  core-js: false
  electron: true
  electron-winstaller: false
  esbuild: true
