# https://pnpm.io/pnpm-workspace_yaml
packages:
  - "apps/*"
  - "packages/*"
catalog:
  typescript: 5.5.3
  "@typescript-eslint/eslint-plugin": 7.16.1
  "@typescript-eslint/parser": 7.16.1
  "@types/node": 20.14.10
  prettier: 3.3.1
  eslint: 8.56.0
  eslint-config-prettier: 9.1.0
  eslint-plugin-prettier: 5.1.3
  vitest: 2.1.6
