packages:
  - apps/*
  - packages/*

catalog:
  '@types/node': 22.15.26
  rimraf: 6.0.1
  ts-essentials: 10.1.1
  typescript: 6.0.0-beta
  vitest: 3.2.1

onlyBuiltDependencies:
  - electron
  - esbuild

useNodeVersion: 22.15.1
