import { _applyDelay } from '../RundownService.js';

describe('applyDelay()', () => {
  it('applies its duration to following events', () => {
    const rundown = [
      {
        title: '',
        subtitle: '',
        presenter: '',
        note: '',
        endAction: 'none',
        timerType: 'count-down',
        timeStart: 600000,
        timeEnd: 1200000,
        duration: 600000,
        isPublic: true,
        skip: false,
        colour: '',
        user0: '',
        user1: '',
        user2: '',
        user3: '',
        user4: '',
        user5: '',
        user6: '',
        user7: '',
        user8: '',
        user9: '',
        type: 'event',
        revision: 4,
        id: '659e1',
      },
      {
        duration: 600000,
        type: 'delay',
        revision: 0,
        id: '07986',
      },
      {
        title: '',
        subtitle: '',
        presenter: '',
        note: '',
        endAction: 'none',
        timerType: 'count-down',
        timeStart: 600000,
        timeEnd: 1200000,
        duration: 600000,
        isPublic: true,
        skip: false,
        colour: '',
        user0: '',
        user1: '',
        user2: '',
        user3: '',
        user4: '',
        user5: '',
        user6: '',
        user7: '',
        user8: '',
        user9: '',
        type: 'event',
        revision: 4,
        id: 'd48c2',
      },
    ];
    const eventId = rundown[1].id;

    const updatedRundown = _applyDelay(eventId, rundown);

    expect(updatedRundown.length).toBe(2);
    expect(rundown.length).toBe(3);
    expect(updatedRundown[0].timeStart).toBe(rundown[0].timeStart);
    expect(updatedRundown[1].timeStart).toBe(rundown[1].duration + rundown[2].timeStart);
  });
  it('stops propagating on blocks', () => {
    const rundown = [
      {
        title: '',
        subtitle: '',
        presenter: '',
        note: '',
        endAction: 'none',
        timerType: 'count-down',
        timeStart: 600000,
        timeEnd: 1200000,
        duration: 600000,
        isPublic: true,
        skip: false,
        colour: '',
        user0: '',
        user1: '',
        user2: '',
        user3: '',
        user4: '',
        user5: '',
        user6: '',
        user7: '',
        user8: '',
        user9: '',
        type: 'event',
        revision: 0,
        id: '659e1',
      },
      {
        duration: 600000,
        type: 'delay',
        revision: 0,
        id: '07986',
      },
      {
        title: '',
        subtitle: '',
        presenter: '',
        note: '',
        endAction: 'none',
        timerType: 'count-down',
        timeStart: 600000,
        timeEnd: 1200000,
        duration: 600000,
        isPublic: true,
        skip: false,
        colour: '',
        user0: '',
        user1: '',
        user2: '',
        user3: '',
        user4: '',
        user5: '',
        user6: '',
        user7: '',
        user8: '',
        user9: '',
        type: 'event',
        revision: 0,
        id: 'd48c2',
      },
      {
        title: '',
        type: 'block',
        id: '9870d',
      },
      {
        title: '',
        subtitle: '',
        presenter: '',
        note: '',
        endAction: 'none',
        timerType: 'count-down',
        timeStart: 1200000,
        timeEnd: 1800000,
        duration: 600000,
        isPublic: true,
        skip: false,
        colour: '',
        user0: '',
        user1: '',
        user2: '',
        user3: '',
        user4: '',
        user5: '',
        user6: '',
        user7: '',
        user8: '',
        user9: '',
        type: 'event',
        revision: 2,
        id: '2f185',
      },
    ];
    const eventId = rundown[1].id;

    const updatedRundown = _applyDelay(eventId, rundown);

    expect(updatedRundown.length).toBe(4);
    expect(updatedRundown[0].timeStart).toBe(rundown[0].timeStart);
    expect(updatedRundown[1].timeStart).toBe(rundown[1].duration + rundown[2].timeStart);
    expect(updatedRundown[3].timeStart).toBe(rundown[4].timeStart);
  });
  it('only applies given delay', () => {
    const rundown = [
      {
        title: '',
        subtitle: '',
        presenter: '',
        note: '',
        endAction: 'none',
        timerType: 'count-down',
        timeStart: 600000,
        timeEnd: 1200000,
        duration: 600000,
        isPublic: true,
        skip: false,
        colour: '',
        user0: '',
        user1: '',
        user2: '',
        user3: '',
        user4: '',
        user5: '',
        user6: '',
        user7: '',
        user8: '',
        user9: '',
        type: 'event',
        revision: 0,
        id: '659e1',
      },
      {
        duration: 600000,
        type: 'delay',
        revision: 0,
        id: '07986',
      },
      {
        title: '',
        subtitle: '',
        presenter: '',
        note: '',
        endAction: 'none',
        timerType: 'count-down',
        timeStart: 1200000,
        timeEnd: 1200000,
        duration: 0,
        isPublic: true,
        skip: false,
        colour: '',
        user0: '',
        user1: '',
        user2: '',
        user3: '',
        user4: '',
        user5: '',
        user6: '',
        user7: '',
        user8: '',
        user9: '',
        type: 'event',
        revision: 0,
        id: '1c48f',
      },
      {
        duration: 1200000,
        type: 'delay',
        revision: 0,
        id: '7db42',
      },
      {
        title: '',
        subtitle: '',
        presenter: '',
        note: '',
        endAction: 'none',
        timerType: 'count-down',
        timeStart: 600000,
        timeEnd: 1200000,
        duration: 600000,
        isPublic: true,
        skip: false,
        colour: '',
        user0: '',
        user1: '',
        user2: '',
        user3: '',
        user4: '',
        user5: '',
        user6: '',
        user7: '',
        user8: '',
        user9: '',
        type: 'event',
        revision: 0,
        id: 'd48c2',
      },
      {
        title: '',
        type: 'block',
        id: '9870d',
      },
      {
        title: '',
        subtitle: '',
        presenter: '',
        note: '',
        endAction: 'none',
        timerType: 'count-down',
        timeStart: 1200000,
        timeEnd: 1800000,
        duration: 600000,
        isPublic: true,
        skip: false,
        colour: '',
        user0: '',
        user1: '',
        user2: '',
        user3: '',
        user4: '',
        user5: '',
        user6: '',
        user7: '',
        user8: '',
        user9: '',
        type: 'event',
        revision: 0,
        id: '2f185',
      },
    ];
    const eventId = rundown[1].id;

    const updatedRundown = _applyDelay(eventId, rundown);

    expect(updatedRundown.length).toBe(6);
    expect(updatedRundown[0].timeStart).toBe(rundown[0].timeStart);
    expect(updatedRundown[1].timeStart).toBe(rundown[1].duration + rundown[2].timeStart);
    expect(updatedRundown[3].timeStart).toBe(rundown[1].duration + rundown[4].timeStart);
  });
});
