import { EndAction, OntimeRundown, SupportedEvent, TimerType } from 'ontime-types';

export const data: OntimeRundown = [
  {
    title: 'Albania',
    subtitle: 'Sekret',
    presenter: 'Ronela Hajati',
    note: 'SF1.01',
    endAction: EndAction.None,
    timerType: TimerType.CountDown,
    timeStart: 36000000,
    timeEnd: 37200000,
    duration: 1200000,
    isPublic: true,
    skip: false,
    colour: '',
    user0: '',
    user1: '',
    user2: '',
    user3: '',
    user4: '',
    user5: '',
    user6: '',
    user7: '',
    user8: '',
    user9: '',
    type: SupportedEvent.Event,
    revision: 0,
    id: '32d31',
  },
  {
    title: 'Latvia',
    subtitle: 'Eat Your Salad',
    presenter: 'Citi Zeni',
    note: 'SF1.02',
    endAction: EndAction.None,
    timerType: TimerType.CountDown,
    timeStart: 37500000,
    timeEnd: 38700000,
    duration: 1200000,
    isPublic: true,
    skip: false,
    colour: '',
    user0: '',
    user1: '',
    user2: '',
    user3: '',
    user4: '',
    user5: '',
    user6: '',
    user7: '',
    user8: '',
    user9: '',
    type: SupportedEvent.Event,
    revision: 0,
    id: '21cd2',
  },
  {
    title: 'Lithuania',
    subtitle: 'Sentimentai',
    presenter: 'Monika Liu',
    note: 'SF1.03',
    endAction: EndAction.None,
    timerType: TimerType.CountDown,
    timeStart: 39000000,
    timeEnd: 40200000,
    duration: 1200000,
    isPublic: true,
    skip: false,
    colour: '',
    user0: '',
    user1: '',
    user2: '',
    user3: '',
    user4: '',
    user5: '',
    user6: '',
    user7: '',
    user8: '',
    user9: '',
    type: SupportedEvent.Event,
    revision: 0,
    id: '0b371',
  },
  {
    title: 'Switzerland',
    subtitle: 'Boys Do Cry',
    presenter: 'Marius Bear',
    note: 'SF1.04',
    endAction: EndAction.None,
    timerType: TimerType.CountDown,
    timeStart: 40500000,
    timeEnd: 41700000,
    duration: 1200000,
    isPublic: true,
    skip: false,
    colour: '',
    user0: '',
    user1: '',
    user2: '',
    user3: '',
    user4: '',
    user5: '',
    user6: '',
    user7: '',
    user8: '',
    user9: '',
    type: SupportedEvent.Event,
    revision: 0,
    id: '3cd28',
  },
  {
    title: 'Slovenia',
    subtitle: 'Disko',
    presenter: 'LPS',
    note: 'SF1.05',
    endAction: EndAction.None,
    timerType: TimerType.CountDown,
    timeStart: 42000000,
    timeEnd: 43200000,
    duration: 1200000,
    isPublic: true,
    skip: false,
    colour: '',
    user0: '',
    user1: '',
    user2: '',
    user3: '',
    user4: '',
    user5: '',
    user6: '',
    user7: '',
    user8: '',
    user9: '',
    type: SupportedEvent.Event,
    revision: 0,
    id: 'e457f',
  },
  {
    title: 'Lunch break',
    type: SupportedEvent.Block,
    id: '01e85',
  },
  {
    title: 'Ukraine',
    subtitle: 'Stefania',
    presenter: 'Kalush Orchestra',
    note: 'SF1.06',
    endAction: EndAction.None,
    timerType: TimerType.CountDown,
    timeStart: 47100000,
    timeEnd: 48300000,
    duration: 1200000,
    isPublic: true,
    skip: false,
    colour: '',
    user0: '',
    user1: '',
    user2: '',
    user3: '',
    user4: '',
    user5: '',
    user6: '',
    user7: '',
    user8: '',
    user9: '',
    type: SupportedEvent.Event,
    revision: 0,
    id: '1c420',
  },
  {
    title: 'Bulgaria',
    subtitle: 'Intention',
    presenter: 'Intelligent Music Project',
    note: 'SF1.07',
    endAction: EndAction.None,
    timerType: TimerType.CountDown,
    timeStart: 48600000,
    timeEnd: 49800000,
    duration: 1200000,
    isPublic: true,
    skip: false,
    colour: '',
    user0: '',
    user1: '',
    user2: '',
    user3: '',
    user4: '',
    user5: '',
    user6: '',
    user7: '',
    user8: '',
    user9: '',
    type: SupportedEvent.Event,
    revision: 0,
    id: 'b7737',
  },
  {
    title: 'Netherlands',
    subtitle: 'De Diepte',
    presenter: 'S10',
    note: 'SF1.08',
    endAction: EndAction.None,
    timerType: TimerType.CountDown,
    timeStart: 50100000,
    timeEnd: 51300000,
    duration: 1200000,
    isPublic: true,
    skip: false,
    colour: '',
    user0: '',
    user1: '',
    user2: '',
    user3: '',
    user4: '',
    user5: '',
    user6: '',
    user7: '',
    user8: '',
    user9: '',
    type: SupportedEvent.Event,
    revision: 0,
    id: 'd3a80',
  },
  {
    title: 'Moldova',
    subtitle: 'Trenuletul',
    presenter: 'Zdob si Zdub',
    note: 'SF1.09',
    endAction: EndAction.None,
    timerType: TimerType.CountDown,
    timeStart: 51600000,
    timeEnd: 52800000,
    duration: 1200000,
    isPublic: true,
    skip: false,
    colour: '',
    user0: '',
    user1: '',
    user2: '',
    user3: '',
    user4: '',
    user5: '',
    user6: '',
    user7: '',
    user8: '',
    user9: '',
    type: SupportedEvent.Event,
    revision: 0,
    id: '8276c',
  },
  {
    title: 'Portugal',
    subtitle: 'Saudade Saudade',
    presenter: 'Maro',
    note: 'SF1.10',
    endAction: EndAction.None,
    timerType: TimerType.CountDown,
    timeStart: 53100000,
    timeEnd: 54300000,
    duration: 1200000,
    isPublic: true,
    skip: false,
    colour: '',
    user0: '',
    user1: '',
    user2: '',
    user3: '',
    user4: '',
    user5: '',
    user6: '',
    user7: '',
    user8: '',
    user9: '',
    type: SupportedEvent.Event,
    revision: 0,
    id: '2340b',
  },
  {
    title: 'Afternoon break',
    type: SupportedEvent.Block,
    id: 'cb90b',
  },
  {
    title: 'Croatia',
    subtitle: 'Guilty Pleasure',
    presenter: 'Mia Dimsic',
    note: 'SF1.11',
    endAction: EndAction.None,
    timerType: TimerType.CountDown,
    timeStart: 56100000,
    timeEnd: 57300000,
    duration: 1200000,
    isPublic: true,
    skip: false,
    colour: '',
    user0: '',
    user1: '',
    user2: '',
    user3: '',
    user4: '',
    user5: '',
    user6: '',
    user7: '',
    user8: '',
    user9: '',
    type: SupportedEvent.Event,
    revision: 0,
    id: '503c4',
  },
  {
    title: 'Denmark',
    subtitle: 'The Show',
    presenter: 'Reddi',
    note: 'SF1.12',
    endAction: EndAction.None,
    timerType: TimerType.CountDown,
    timeStart: 57600000,
    timeEnd: 58800000,
    duration: 1200000,
    isPublic: true,
    skip: false,
    colour: '',
    user0: '',
    user1: '',
    user2: '',
    user3: '',
    user4: '',
    user5: '',
    user6: '',
    user7: '',
    user8: '',
    user9: '',
    type: SupportedEvent.Event,
    revision: 0,
    id: '5e965',
  },
  {
    title: 'Austria',
    subtitle: 'Halo',
    presenter: 'LUM!X & Pia Maria',
    note: 'SF1.13',
    endAction: EndAction.None,
    timerType: TimerType.CountDown,
    timeStart: 59100000,
    timeEnd: 60300000,
    duration: 1200000,
    isPublic: true,
    skip: false,
    colour: '',
    user0: '',
    user1: '',
    user2: '',
    user3: '',
    user4: '',
    user5: '',
    user6: '',
    user7: '',
    user8: '',
    user9: '',
    type: SupportedEvent.Event,
    revision: 0,
    id: 'bab4a',
  },
  {
    title: 'Greece',
    subtitle: 'Die Together',
    presenter: 'Amanda Tenfjord',
    note: 'SF1.14',
    endAction: EndAction.None,
    timerType: TimerType.CountDown,
    timeStart: 60600000,
    timeEnd: 61800000,
    duration: 1200000,
    isPublic: true,
    skip: false,
    colour: '',
    user0: '',
    user1: '',
    user2: '',
    user3: '',
    user4: '',
    user5: '',
    user6: '',
    user7: '',
    user8: '',
    user9: '',
    type: SupportedEvent.Event,
    revision: 0,
    id: 'd3eb1',
  },
];
